### PR TITLE
Ruby style guide compliance

### PR DESCRIPTION
**Pull request by tom-lord**
I haven't changed any behaviour of your code.....

Just fixed lots of whitespace, and improved the way you're handling exceptions.
Figured you might appreciate the clean-up, in case you decide to continue working on this :)

p.s. Some of your code seems broken?... (`undefined method 'lift' for CongruenceSolver:Module>`) - but I didn't bother looking into what's gone wrong. (Have you not checked the `Gemfile` into source control??`

### CODE REVIEW

**Comment by laneb** [comment]
Thanks for the style suggestions! I'll take a look at your edits and see how I can make changes to my style but I probably won't merge - mostly because I'd like to make the edits myself (since this project was mostly for self-teaching), but also because at least one edit here actually does change the functionality of the project. I should have paid more attention to the development section of the README - one step should be to run "rake compile_c" to compile the extension for testing. It will compile the extension into a shared library called congruence_solver.so and place it in the lib/congruence_solver directory, so you will stop receiving invalid require and no method errors. I'll fix that right now!

**Comment by laneb** [comment]
Upon further thought I suppose that functionality should be in the rake install command.

**Comment by tom-lord** [comment]
The `rake compile_c` task also does not work for me. There are multiple issues here:
1. Your code assumes I have the `rake-compiler` gem installed, and does not specify this in a Gemfile or whatever.
2. After fixing that, I then get the following error:
   
   > rake compile_c
   >   rake aborted!
   >   Don't know how to build task 'ext/congruence_solver/extconf.rb' (see --tasks)
3. Even if this all worked, then the task would still fail because of this line:
   
   > system "rmdir /s /q tmp"
   >     # => rmdir: failed to remove ‘/s’: No such file or directory

It looks like you're writing code on Windows (which I could not recommend to begin with), and this line makes an assumption about your operating system. You should instead be using the [FileUtils](http://ruby-doc.org/stdlib-2.3.0/libdoc/fileutils/rdoc/FileUtils.html) standard library.

**Comment by tom-lord** [comment]
I've re-added that `require` for now, although that breaks the tool for me. With this back in place, the project is 100% functionally identical to your original code.

As I say, basically all I changed was white-space and cleaning up how you were raising/re-raising/rescuing from exceptions.

**Comment by laneb** [comment]
rake-compiler is specified in the .gemspec. I hadn't realized that my Gemfile was excluded from the VC, which I have fixed. I have since made significant changes to the rakefile, including that it distinguishes between windows and not-windows in deciding what rm commands/options to use. An additional problem which you were likely to have is that the files in the submodule containing the extension would not have been cloned with the repository, because git makes you clone them separately. This should also be addressed in the current push. Frankly, I hadn't prepared this project to be shared for development because I don't plan to collaborate actively with others and because my priority so far has been getting the gem to install properly.

**Comment by laneb** [comment]
As for using Windows - my personal machine is Windows, it's what I have access to at the moment.

**Pull request closed without merging**
